### ISSUE TITLE
Trying to Build with AOSP Source but getting build failed

### ISSUE THREAD

**Issue by umerfaruque** [Manish4586/android_device_xiaomi_jasmine#5]
I want to know which source like AOSP, lineage etc will be suitable for this device tree

**Comment by Manish4586** [comment]
use pe-9.0 branch to build aosp

**Comment by umerfaruque** [comment]
I am using following repository

1 AOSP latest source code
2 Manish4586/android_device_xiaomi_jasmine_sprout pe-9.0 branch
3 Manish4586/android_vendor_xiaomi_jasmine_sprout android-9.0 branch
4 Manish4586/android_kernel_xiaomi_jasmine_sprout dev branch

and getting following error. please help

     52. aosp_jasmine_sprout-eng
     53. aosp_jasmine_sprout-user
     54. aosp_jasmine_sprout-userdebug

Which would you like? [aosp_arm-eng] 52
vendor/xiaomi/jasmine_sprout/jasmine_sprout-vendor.mk:1984: error: _nic.PRODUCTS.[[device/xiaomi/jasmine_sprout/aosp_jasmine_sprout.mk]]: "vendor/aosp/config/common_full_phone.mk" does not exist.
11:24:02 dumpvars failed with: exit status 1

**Comment by umerfaruque** [comment]
I have built successfully with lineage source code but it's not booting, please help

**Comment by Manish4586** [comment]
lineageos tree?

**Comment by umerfaruque** [comment]
Yes with lineageOS tree

**Comment by Manish4586** [comment]
16.0 tree?

**Comment by Manish4586** [comment]
16.0 tree?

**Comment by umerfaruque** [comment]
yes with 16.0 tree
